version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432


  flask:
    build: .
    container_name: cats
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres


