version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    command: sh -c "(nohup docker-entrypoint.sh postgres > /dev/null 2>&1 &) && sleep 3 && psql -d postgres -f init.sql &
      while :;do :;done"

  web:
    build: .
    container_name: web
    env_file:
      - .env
    ports:
      - 80:8080
    depends_on:
      - db
    command: python main.py

volumes:
  pg_data: